CREATE TABLE `wp_termmeta` (  `meta_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,  `term_id` bigint(20) unsigned NOT NULL DEFAULT '0',  `meta_key` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,  `meta_value` longtext COLLATE utf8mb4_unicode_520_ci,  PRIMARY KEY (`meta_id`),  KEY `term_id` (`term_id`),  KEY `meta_key` (`meta_key`(191))) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40000 ALTER TABLE `wp_termmeta` DISABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 0;
SET UNIQUE_CHECKS = 0;
INSERT INTO `wp_termmeta` VALUES('2', '37', 'order', '0');
INSERT INTO `wp_termmeta` VALUES('6', '41', 'order', '0');
INSERT INTO `wp_termmeta` VALUES('9', '41', 'product_count_product_cat', '3');
INSERT INTO `wp_termmeta` VALUES('10', '37', 'product_count_product_cat', '0');
INSERT INTO `wp_termmeta` VALUES('15', '37', 'display_type', '');
INSERT INTO `wp_termmeta` VALUES('16', '37', 'thumbnail_id', '48');
INSERT INTO `wp_termmeta` VALUES('17', '41', 'display_type', '');
INSERT INTO `wp_termmeta` VALUES('18', '41', 'thumbnail_id', '25');
/*!40000 ALTER TABLE `wp_termmeta` ENABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS = 1;
