CREATE TABLE `wp_term_relationships` (  `object_id` bigint(20) unsigned NOT NULL DEFAULT '0',  `term_taxonomy_id` bigint(20) unsigned NOT NULL DEFAULT '0',  `term_order` int(11) NOT NULL DEFAULT '0',  PRIMARY KEY (`object_id`,`term_taxonomy_id`),  KEY `term_taxonomy_id` (`term_taxonomy_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40000 ALTER TABLE `wp_term_relationships` DISABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 0;
SET UNIQUE_CHECKS = 0;
INSERT INTO `wp_term_relationships` VALUES('19', '2', '0');
INSERT INTO `wp_term_relationships` VALUES('19', '41', '0');
INSERT INTO `wp_term_relationships` VALUES('22', '4', '0');
INSERT INTO `wp_term_relationships` VALUES('22', '33', '0');
INSERT INTO `wp_term_relationships` VALUES('22', '35', '0');
INSERT INTO `wp_term_relationships` VALUES('22', '41', '0');
INSERT INTO `wp_term_relationships` VALUES('31', '2', '0');
INSERT INTO `wp_term_relationships` VALUES('31', '41', '0');
INSERT INTO `wp_term_relationships` VALUES('34', '2', '0');
INSERT INTO `wp_term_relationships` VALUES('34', '41', '0');
INSERT INTO `wp_term_relationships` VALUES('37', '2', '0');
INSERT INTO `wp_term_relationships` VALUES('37', '41', '0');
INSERT INTO `wp_term_relationships` VALUES('40', '4', '0');
INSERT INTO `wp_term_relationships` VALUES('40', '33', '0');
INSERT INTO `wp_term_relationships` VALUES('40', '34', '0');
INSERT INTO `wp_term_relationships` VALUES('40', '37', '0');
INSERT INTO `wp_term_relationships` VALUES('47', '2', '0');
INSERT INTO `wp_term_relationships` VALUES('47', '37', '0');
INSERT INTO `wp_term_relationships` VALUES('50', '2', '0');
INSERT INTO `wp_term_relationships` VALUES('50', '37', '0');
INSERT INTO `wp_term_relationships` VALUES('53', '2', '0');
INSERT INTO `wp_term_relationships` VALUES('53', '37', '0');
INSERT INTO `wp_term_relationships` VALUES('56', '2', '0');
INSERT INTO `wp_term_relationships` VALUES('56', '37', '0');
INSERT INTO `wp_term_relationships` VALUES('60', '2', '0');
INSERT INTO `wp_term_relationships` VALUES('60', '37', '0');
INSERT INTO `wp_term_relationships` VALUES('104', '2', '0');
INSERT INTO `wp_term_relationships` VALUES('107', '2', '0');
INSERT INTO `wp_term_relationships` VALUES('110', '2', '0');
INSERT INTO `wp_term_relationships` VALUES('110', '41', '0');
INSERT INTO `wp_term_relationships` VALUES('214', '2', '0');
INSERT INTO `wp_term_relationships` VALUES('214', '41', '0');
INSERT INTO `wp_term_relationships` VALUES('3552', '30', '0');
INSERT INTO `wp_term_relationships` VALUES('3577', '2', '0');
INSERT INTO `wp_term_relationships` VALUES('3577', '41', '0');
INSERT INTO `wp_term_relationships` VALUES('3599', '30', '0');
INSERT INTO `wp_term_relationships` VALUES('3600', '30', '0');
INSERT INTO `wp_term_relationships` VALUES('3628', '2', '0');
INSERT INTO `wp_term_relationships` VALUES('3628', '41', '0');
INSERT INTO `wp_term_relationships` VALUES('3629', '2', '0');
INSERT INTO `wp_term_relationships` VALUES('3631', '43', '0');
INSERT INTO `wp_term_relationships` VALUES('3632', '44', '0');
INSERT INTO `wp_term_relationships` VALUES('3633', '44', '0');
INSERT INTO `wp_term_relationships` VALUES('3634', '10', '0');
INSERT INTO `wp_term_relationships` VALUES('3634', '45', '0');
INSERT INTO `wp_term_relationships` VALUES('3635', '10', '0');
INSERT INTO `wp_term_relationships` VALUES('3635', '45', '0');
INSERT INTO `wp_term_relationships` VALUES('3636', '10', '0');
INSERT INTO `wp_term_relationships` VALUES('3636', '45', '0');
INSERT INTO `wp_term_relationships` VALUES('3643', '47', '0');
INSERT INTO `wp_term_relationships` VALUES('3644', '47', '0');
INSERT INTO `wp_term_relationships` VALUES('3645', '47', '0');
INSERT INTO `wp_term_relationships` VALUES('3646', '47', '0');
INSERT INTO `wp_term_relationships` VALUES('3647', '47', '0');
/*!40000 ALTER TABLE `wp_term_relationships` ENABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS = 1;
