CREATE TABLE `wp_woocommerce_order_items` (  `order_item_id` bigint(20) NOT NULL AUTO_INCREMENT,  `order_item_name` longtext COLLATE utf8mb4_unicode_520_ci NOT NULL,  `order_item_type` varchar(200) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '',  `order_id` bigint(20) NOT NULL,  PRIMARY KEY (`order_item_id`),  KEY `order_id` (`order_id`)) ENGINE=InnoDB AUTO_INCREMENT=123 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40000 ALTER TABLE `wp_woocommerce_order_items` DISABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 0;
SET UNIQUE_CHECKS = 0;
INSERT INTO `wp_woocommerce_order_items` VALUES('1', 'Custom Supply', 'line_item', '3659');
INSERT INTO `wp_woocommerce_order_items` VALUES('2', 'Parcel For Me : Standard post', 'shipping', '3659');
INSERT INTO `wp_woocommerce_order_items` VALUES('3', 'AU-GST-1', 'tax', '3659');
INSERT INTO `wp_woocommerce_order_items` VALUES('4', 'Ghost Rider', 'line_item', '3666');
INSERT INTO `wp_woocommerce_order_items` VALUES('5', 'Custom Supply', 'line_item', '3666');
INSERT INTO `wp_woocommerce_order_items` VALUES('6', 'Parcel For Me : Standard post', 'shipping', '3666');
INSERT INTO `wp_woocommerce_order_items` VALUES('7', 'AU-GST-1', 'tax', '3666');
INSERT INTO `wp_woocommerce_order_items` VALUES('8', 'Ghost Rider', 'line_item', '3668');
INSERT INTO `wp_woocommerce_order_items` VALUES('9', 'Parcel For Me : ', 'shipping', '3668');
INSERT INTO `wp_woocommerce_order_items` VALUES('10', 'AU-GST-1', 'tax', '3668');
INSERT INTO `wp_woocommerce_order_items` VALUES('11', 'Victory Bros.', 'line_item', '3669');
INSERT INTO `wp_woocommerce_order_items` VALUES('12', 'Parcel For Me : Courier', 'shipping', '3669');
INSERT INTO `wp_woocommerce_order_items` VALUES('13', 'AU-GST-1', 'tax', '3669');
INSERT INTO `wp_woocommerce_order_items` VALUES('14', 'Bushcraft', 'line_item', '3670');
INSERT INTO `wp_woocommerce_order_items` VALUES('15', 'Supreme', 'line_item', '3670');
INSERT INTO `wp_woocommerce_order_items` VALUES('16', 'Parcel For Me : Express by 10am', 'shipping', '3670');
INSERT INTO `wp_woocommerce_order_items` VALUES('17', 'AU-GST-1', 'tax', '3670');
INSERT INTO `wp_woocommerce_order_items` VALUES('18', 'Custom Supply', 'line_item', '3671');
INSERT INTO `wp_woocommerce_order_items` VALUES('19', 'Ghost Rider', 'line_item', '3671');
INSERT INTO `wp_woocommerce_order_items` VALUES('20', 'Parcel For Me : Express by 5:30pm', 'shipping', '3671');
INSERT INTO `wp_woocommerce_order_items` VALUES('21', 'AU-GST-1', 'tax', '3671');
INSERT INTO `wp_woocommerce_order_items` VALUES('22', 'Victory Bros.', 'line_item', '3673');
INSERT INTO `wp_woocommerce_order_items` VALUES('23', 'Parcel For Me : Express by 10am', 'shipping', '3673');
INSERT INTO `wp_woocommerce_order_items` VALUES('24', 'AU-GST-1', 'tax', '3673');
INSERT INTO `wp_woocommerce_order_items` VALUES('25', 'Custom Supply', 'line_item', '3674');
INSERT INTO `wp_woocommerce_order_items` VALUES('26', 'Victory Bros.', 'line_item', '3674');
INSERT INTO `wp_woocommerce_order_items` VALUES('27', 'Supreme', 'line_item', '3674');
INSERT INTO `wp_woocommerce_order_items` VALUES('28', 'Custom Supply', 'line_item', '3674');
INSERT INTO `wp_woocommerce_order_items` VALUES('29', 'Parcel For Me : Express by 10am', 'shipping', '3674');
INSERT INTO `wp_woocommerce_order_items` VALUES('30', 'AU-GST-1', 'tax', '3674');
INSERT INTO `wp_woocommerce_order_items` VALUES('31', 'Santa Rosa', 'line_item', '3675');
INSERT INTO `wp_woocommerce_order_items` VALUES('32', 'Parcel For Me : Express by 10am', 'shipping', '3675');
INSERT INTO `wp_woocommerce_order_items` VALUES('33', 'AU-GST-1', 'tax', '3675');
INSERT INTO `wp_woocommerce_order_items` VALUES('34', 'Supreme', 'line_item', '3676');
INSERT INTO `wp_woocommerce_order_items` VALUES('35', 'Victory Bros.', 'line_item', '3676');
INSERT INTO `wp_woocommerce_order_items` VALUES('36', 'Parcel For Me : Standard post', 'shipping', '3676');
INSERT INTO `wp_woocommerce_order_items` VALUES('37', 'AU-GST-1', 'tax', '3676');
INSERT INTO `wp_woocommerce_order_items` VALUES('38', 'Custom Supply', 'line_item', '3677');
INSERT INTO `wp_woocommerce_order_items` VALUES('39', 'Parcel For Me : Standard post', 'shipping', '3677');
INSERT INTO `wp_woocommerce_order_items` VALUES('40', 'AU-GST-1', 'tax', '3677');
INSERT INTO `wp_woocommerce_order_items` VALUES('41', 'Bushcraft', 'line_item', '3678');
INSERT INTO `wp_woocommerce_order_items` VALUES('42', 'Parcel For Me : Standard post', 'shipping', '3678');
INSERT INTO `wp_woocommerce_order_items` VALUES('43', 'Ghost Rider', 'line_item', '3679');
INSERT INTO `wp_woocommerce_order_items` VALUES('44', 'Custom Supply', 'line_item', '3679');
INSERT INTO `wp_woocommerce_order_items` VALUES('45', 'Parcel For Me : Standard post', 'shipping', '3679');
INSERT INTO `wp_woocommerce_order_items` VALUES('46', 'Supreme', 'line_item', '3680');
INSERT INTO `wp_woocommerce_order_items` VALUES('47', 'Parcel For Me : Standard post', 'shipping', '3680');
INSERT INTO `wp_woocommerce_order_items` VALUES('48', 'Ghost Rider', 'line_item', '3681');
INSERT INTO `wp_woocommerce_order_items` VALUES('49', 'Santa Rosa', 'line_item', '3681');
INSERT INTO `wp_woocommerce_order_items` VALUES('50', 'Parcel For Me : Standard post', 'shipping', '3681');
INSERT INTO `wp_woocommerce_order_items` VALUES('51', 'Victory Bros.', 'line_item', '3682');
INSERT INTO `wp_woocommerce_order_items` VALUES('52', 'Custom Supply', 'line_item', '3682');
INSERT INTO `wp_woocommerce_order_items` VALUES('53', 'Parcel For Me : Express by 10am', 'shipping', '3682');
INSERT INTO `wp_woocommerce_order_items` VALUES('54', 'Victory Bros.', 'line_item', '3683');
INSERT INTO `wp_woocommerce_order_items` VALUES('55', 'Parcel For Me : Express by 12pm', 'shipping', '3683');
INSERT INTO `wp_woocommerce_order_items` VALUES('56', 'Custom Supply', 'line_item', '3684');
INSERT INTO `wp_woocommerce_order_items` VALUES('57', 'Parcel For Me : Saturday by 5.30pm', 'shipping', '3684');
INSERT INTO `wp_woocommerce_order_items` VALUES('58', 'Supreme', 'line_item', '3686');
INSERT INTO `wp_woocommerce_order_items` VALUES('59', 'Parcel For Me : ', 'shipping', '3686');
INSERT INTO `wp_woocommerce_order_items` VALUES('60', 'AU-GST-1', 'tax', '3686');
INSERT INTO `wp_woocommerce_order_items` VALUES('61', 'Victory Bros.', 'line_item', '3687');
INSERT INTO `wp_woocommerce_order_items` VALUES('62', 'Parcel For Me : ', 'shipping', '3687');
INSERT INTO `wp_woocommerce_order_items` VALUES('63', 'AU-GST-1', 'tax', '3687');
INSERT INTO `wp_woocommerce_order_items` VALUES('64', 'Custom Supply', 'line_item', '3689');
INSERT INTO `wp_woocommerce_order_items` VALUES('65', 'Ghost Rider', 'line_item', '3689');
INSERT INTO `wp_woocommerce_order_items` VALUES('66', 'Parcel For Me : Courier', 'shipping', '3689');
INSERT INTO `wp_woocommerce_order_items` VALUES('67', 'Victory Bros.', 'line_item', '3690');
INSERT INTO `wp_woocommerce_order_items` VALUES('68', 'Parcel For Me : Collect - Standard', 'shipping', '3690');
INSERT INTO `wp_woocommerce_order_items` VALUES('69', 'Custom Supply', 'line_item', '3691');
INSERT INTO `wp_woocommerce_order_items` VALUES('70', 'Supreme', 'line_item', '3691');
INSERT INTO `wp_woocommerce_order_items` VALUES('71', 'Parcel For Me : Collect - Next Day by 12pm', 'shipping', '3691');
INSERT INTO `wp_woocommerce_order_items` VALUES('72', 'Custom Supply', 'line_item', '3692');
INSERT INTO `wp_woocommerce_order_items` VALUES('73', 'Parcel For Me : Collect - Next Day by 12pm', 'shipping', '3692');
INSERT INTO `wp_woocommerce_order_items` VALUES('74', 'Victory Bros.', 'line_item', '3693');
INSERT INTO `wp_woocommerce_order_items` VALUES('75', 'Parcel For Me : Collect - Next Day by 12pm', 'shipping', '3693');
INSERT INTO `wp_woocommerce_order_items` VALUES('76', 'Custom Supply', 'line_item', '3694');
INSERT INTO `wp_woocommerce_order_items` VALUES('77', 'Victory Bros.', 'line_item', '3695');
INSERT INTO `wp_woocommerce_order_items` VALUES('78', 'Parcel For Me : Standard Delivery', 'shipping', '3695');
INSERT INTO `wp_woocommerce_order_items` VALUES('79', 'Victory Bros.', 'line_item', '3696');
INSERT INTO `wp_woocommerce_order_items` VALUES('80', 'Parcel For Me : Next Day Delivery', 'shipping', '3696');
INSERT INTO `wp_woocommerce_order_items` VALUES('81', 'Custom Supply', 'line_item', '3697');
INSERT INTO `wp_woocommerce_order_items` VALUES('82', 'Parcel For Me : Next Day Delivery', 'shipping', '3697');
INSERT INTO `wp_woocommerce_order_items` VALUES('83', 'Ghost Rider', 'line_item', '3698');
INSERT INTO `wp_woocommerce_order_items` VALUES('84', 'Parcel For Me : Saturday Delivery', 'shipping', '3698');
INSERT INTO `wp_woocommerce_order_items` VALUES('85', 'Ghost Rider', 'line_item', '3699');
INSERT INTO `wp_woocommerce_order_items` VALUES('86', 'Santa Rosa', 'line_item', '3699');
INSERT INTO `wp_woocommerce_order_items` VALUES('87', 'Parcel For Me : Next Day Delivery', 'shipping', '3699');
INSERT INTO `wp_woocommerce_order_items` VALUES('88', 'Supreme', 'line_item', '3701');
INSERT INTO `wp_woocommerce_order_items` VALUES('89', 'Parcel For Me : Standard Delivery', 'shipping', '3701');
INSERT INTO `wp_woocommerce_order_items` VALUES('90', 'Supreme', 'line_item', '3702');
INSERT INTO `wp_woocommerce_order_items` VALUES('91', 'Parcel For Me : Standard Delivery', 'shipping', '3702');
INSERT INTO `wp_woocommerce_order_items` VALUES('92', 'Ghost Rider', 'line_item', '3703');
INSERT INTO `wp_woocommerce_order_items` VALUES('93', 'Parcel For Me : Sunday Delivery', 'shipping', '3703');
INSERT INTO `wp_woocommerce_order_items` VALUES('94', 'Custom Supply', 'line_item', '3704');
INSERT INTO `wp_woocommerce_order_items` VALUES('95', 'Parcel For Me : Pre-10', 'shipping', '3704');
INSERT INTO `wp_woocommerce_order_items` VALUES('96', 'Ghost Rider', 'line_item', '3705');
INSERT INTO `wp_woocommerce_order_items` VALUES('97', 'Parcel For Me : Sunday Delivery', 'shipping', '3705');
INSERT INTO `wp_woocommerce_order_items` VALUES('98', 'Supreme', 'line_item', '3706');
INSERT INTO `wp_woocommerce_order_items` VALUES('99', 'Parcel For Me : Sunday Delivery', 'shipping', '3706');
INSERT INTO `wp_woocommerce_order_items` VALUES('100', 'Ghost Rider', 'line_item', '3711');
INSERT INTO `wp_woocommerce_order_items` VALUES('101', 'Parcel For Me : Standard Delivery', 'shipping', '3711');
INSERT INTO `wp_woocommerce_order_items` VALUES('102', 'Ghost Rider', 'line_item', '3715');
INSERT INTO `wp_woocommerce_order_items` VALUES('103', 'Victory Bros.', 'line_item', '3715');
INSERT INTO `wp_woocommerce_order_items` VALUES('104', 'Parcel For Me : Standard Delivery', 'shipping', '3715');
INSERT INTO `wp_woocommerce_order_items` VALUES('105', 'Ghost Rider', 'line_item', '3716');
INSERT INTO `wp_woocommerce_order_items` VALUES('106', 'Parcel For Me : Pre-12', 'shipping', '3716');
INSERT INTO `wp_woocommerce_order_items` VALUES('107', 'Bushcraft', 'line_item', '3717');
INSERT INTO `wp_woocommerce_order_items` VALUES('108', 'Parcel For Me : Click & Collect ', 'shipping', '3717');
INSERT INTO `wp_woocommerce_order_items` VALUES('109', 'Ghost Rider', 'line_item', '3718');
INSERT INTO `wp_woocommerce_order_items` VALUES('110', 'Parcel For Me : Click & Collect ', 'shipping', '3718');
INSERT INTO `wp_woocommerce_order_items` VALUES('111', 'Custom Supply', 'line_item', '3719');
INSERT INTO `wp_woocommerce_order_items` VALUES('112', 'Parcel For Me : Click & Collect ', 'shipping', '3719');
INSERT INTO `wp_woocommerce_order_items` VALUES('113', 'Bushcraft', 'line_item', '3720');
INSERT INTO `wp_woocommerce_order_items` VALUES('114', 'Parcel For Me : Click & Collect ', 'shipping', '3720');
INSERT INTO `wp_woocommerce_order_items` VALUES('115', 'Supreme', 'line_item', '3721');
INSERT INTO `wp_woocommerce_order_items` VALUES('116', 'Parcel For Me : Next Day', 'shipping', '3721');
INSERT INTO `wp_woocommerce_order_items` VALUES('117', 'Supreme', 'line_item', '3722');
INSERT INTO `wp_woocommerce_order_items` VALUES('118', 'Parcel For Me : Pre-10', 'shipping', '3722');
INSERT INTO `wp_woocommerce_order_items` VALUES('119', 'Custom Supply', 'line_item', '3723');
INSERT INTO `wp_woocommerce_order_items` VALUES('120', 'Parcel For Me : Click & Collect ', 'shipping', '3723');
INSERT INTO `wp_woocommerce_order_items` VALUES('121', 'Victory Bros.', 'line_item', '3724');
INSERT INTO `wp_woocommerce_order_items` VALUES('122', 'Parcel For Me : Click & Collect ', 'shipping', '3724');
/*!40000 ALTER TABLE `wp_woocommerce_order_items` ENABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS = 1;
